### ISSUE TITLE
Fantom Partnered with PrimeLabs

### ISSUE THREAD

**Issue by noahdavis22** [Fantom-foundation/substate-cli#5]
Is Fantom Partnered with PrimeLabs? I just saw their testnet for hosting dapps hit 1.4 million TPS. [https://twitter.com/PrimeLab4/status/1565760868775858179](url)

**Comment by b-scholz** [comment]
I am not familiar with PrimeLabs' technology. However, for our purpose, testnets/subnets  are not a very good idea because they don't scale well. Yonsei University and the University of Sydney developed an off-the-chain technology based on substates (funded by Fantom):
https://www.usenix.org/conference/atc21/presentation/kim-yeonsoo

This technology executes transactions in complete isolation without requiring many resources. As a result, the execution of transactions becomes an [embarrassingly parallel problem](https://en.wikipedia.org/wiki/Embarrassingly_parallel) and can be made as fast as you want, having parallel/cluster computers at hand. This is ideal for our work on a new storage system and a new virtual machine. We will shortly publish a blog article on the Off-the-Chain technology.
